### ISSUE TITLE
Random error on undefined function

### ISSUE THREAD

**Issue by alex88** [gagan0123/fix-image-rotation#5]
I'm randomly getting this error when uploading images:

```
2019/01/10 05:39:40 [error] 1698#1698: *80838 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function wp_read_ima
ge_metadata() in /var/www/html/wp-content/plugins/fix-image-rotation/includes/class-fix-image-rotation.php:274
Stack trace:
#0 /var/www/html/wp-content/plugins/fix-image-rotation/includes/class-fix-image-rotation.php(174): Fix_Image_Rotation->do_flip_and_rotate('/tmp/phpcUcXQO', Array)
#1 /var/www/html/wp-content/plugins/fix-image-rotation/includes/class-fix-image-rotation.php(144): Fix_Image_Rotation->fix_image_orientation('/tmp/phpcUcXQ$')
#2 /var/www/html/wp-includes/class-wp-hook.php(286): Fix_Image_Rotation->filter_wp_handle_upload_prefilter(Array)
#3 /var/www/html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#4 /var/www/html/wp-admin/includes/file.php(719): apply_filters('wp_handle_uploa...', Array)
#5 /var/www/html/wp-admin/includes/file.php(923): _wp_handle_upload(Array, Array, NULL, 'wp_handle_uploa...')
#6 /var/www/html/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(" while reading response header from upstream ...
```

using wordpress 5.

Adding a simple

```
require_once ABSPATH . '/wp-admin/includes/image.php';
```

fixed the problem

**Comment by gagan0123** [comment]
Thanks for reporting @alex88 and thanks @bgrande for providing the patch. Will be releasing the plugin with the update after testing out and streamlining the release deployment today.

**Comment by gagan0123** [comment]
Deployed new version, thanks for your help guys 😃
